name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read    # allows reading your repo files
  pages: write      # allows writing to GitHub Pages
  id-token: write   # for OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages  # specify the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # deploy everything in the root (including index.html)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
