name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read    # allows reading your repo files
  pages: write      # allows writing to GitHub Pages
  id-token: write   # for OIDC auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4              # bump to v4

      - name: Configure Pages
        uses: actions/configure-pages@v4      # bump to v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3  # bump to v3
        with:
          path: .                             # root directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4        # bump to v4
