name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read    # allows reading your repo files
  pages: write      # allows writing to GitHub Pages
  id-token: write   # for OIDC authentication (required by configure-pages)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .         

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
